version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: architecture_drawings_development
    volumes:
      - ./docker/mysql-utf8.cnf:/etc/mysql/conf.d/mysql-utf8.cnf
    healthcheck:
        interval: 30s
        timeout: 10s
        retries: 5
  rails:
    build:
      context: .
      dockerfile: docker/Dockerfile.rails
    command: bash docker/rails_entry.sh
    environment:
      SECRET_KEY_BASE: abc123
      BUNDLE_PATH: "/bundle"
      MYSQL_HOST: mysql
      RAILS_ENV: development
      SOLR_HOST: jetty
      SOLR_PORT: 8983
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - solr
    volumes:
      - ./Gemfile.lock:/project_root/Gemfile.lock
  solr:
    build:
      context: .
      dockerfile: docker/Dockerfile.solr
    command: bash /solr/jetty.sh start
    environment:
      JETTY_HOME: "/jetty"
    ports:
      - "8983:8983"
