FROM selenium/standalone-chrome:3.141.59
USER root
RUN apt-get update && apt-get -y install python-pip && pip install selenium

COPY spec spec

RUN useradd -r selenium
USER selenium

ENV BaseURL 'http://rails:3000'
CMD exec python spec/feature/chrome_spec.py
